In [3]:
import numpy as np

In [4]:
np.random.binomial(2, 0.5, size=10)

array([1, 0, 1, 0, 1, 1, 0, 1, 0, 2])

In [5]:
dropout_rate = 0.20
np.random.binomial(1, 1-dropout_rate, size=5)

array([1, 1, 1, 1, 1])

In [6]:
dropout_rate = 0.5
np.random.binomial(1, 1-dropout_rate, size=5)

array([0, 1, 0, 0, 1])

In [7]:
dropout_rate = 0.3
example_output = np.array([0.27, -1.03, 0.67, 0.99, 0.05,-0.37, -2.01, 1.13, -0.07, 0.73])

In [8]:
example_output *= np.random.binomial(1, 1-dropout_rate,example_output.shape)

In [9]:
print(example_output)

[ 0.27 -0.    0.67  0.    0.05 -0.37 -2.01  1.13 -0.    0.73]


### Mean

In [10]:
import numpy as np
dropout_rate = 0.2
example_output = np.array([0.27, -1.03, 0.67, 0.99, 0.05,-0.37, -2.01, 1.13, -0.07, 0.73])
print(f'sum initial {sum(example_output)}')

sum initial 0.36000000000000015


In [11]:
sums = []
for i in range(10000):
    example_output2 = example_output * np.random.binomial(1, 1-dropout_rate, example_output.shape) / (1-dropout_rate)
    sums.append(sum(example_output2))

print(f'mean sum: {np.mean(sums)}')


mean sum: 0.3327912500000002
