In [1]:
import numpy as np

In [2]:
# Passed in gradient from the next layer
# for the purpose of this example we're going to usea 
# a vector of 1's

In [3]:
dvalues = np.ones((3, 3))
print(dvalues)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
dvalues = [[1], [2], [3]] * dvalues
print(dvalues)

[[ 1.  1.  1.]
 [ 8.  8.  8.]
 [27. 27. 27.]]


In [9]:
# we have 3 sets of inputs - samples

In [12]:
inputs = np.array([[1,2,3,2.5],
                   [2,5,-1,2],
                   [-1.5, 2.7, 3.3, -0.8]])

In [20]:
# sum weights of given input
# and multiply by the passed in gradient for this neuron

In [13]:
dweights =  np.dot(inputs.T, dvalues)

In [15]:
print(dweights)

[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


In [16]:
# one bias for each neuron
# biases are the row vector with a shape (1, neurons)

In [17]:
biases = np.array([[2,3,0.5]])

In [18]:
# dbiases - sum values, do this over samples (first axis), keepdims
# since this by default will prorduce a plain list - 
# we explained this in th chapter 4


In [19]:
dbiases = np.sum(dvalues)

In [20]:
dbiases


18.0

In [21]:
dbiases = np.sum(dvalues, axis=0, keepdims=True)

In [22]:
dbiases

array([[6., 6., 6.]])