In [1]:
import numpy as np

In [2]:
# Passed in gradient from the next layer
# for the purpose of this example we're going to usea 
# a vector of 1's

In [3]:
dvalues = np.ones((3, 3))
print(dvalues)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
dvalues = [[1], [2], [3]] * dvalues
print(dvalues)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [9]:
# we have 3 sets of inputs - samples

In [5]:
inputs = np.array([[1,2,3,2.5],
                   [2,5,-1,2],
                   [-1.5, 2.7, 3.3, -0.8]])

In [20]:
# sum weights of given input
# and multiply by the passed in gradient for this neuron

In [6]:
dweights =  np.dot(inputs.T, dvalues)

In [7]:
print(dweights)

[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


### page 35 

In [8]:
import numpy as np

In [9]:
# passed in gradient from the next layer
# for the purpose of this example we're going to use
# an array of incremental gradient values
dvalues = np.ones((3, 3))
dvalues = [[1], [2], [3]] * dvalues
print(dvalues)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [10]:
# One bias for each neuron
# biases are the row vector with a shape (1, neurons)

biases = np.array([[2, 3, 0.5]])

In [11]:
# dbiases - sum values, do this over samples (firsst axis), keep dims
# since this by default will produce  a plain list
# we explained this in the chpter 4

dbiases = np.sum(dvalues, axis= 0, keepdims=True)

In [12]:
print(dbiases)

[[6. 6. 6.]]


### page 36

In [20]:
import numpy as np

In [21]:
# Example layer outputs
z = np.array([[1,2,-3,-4],[2,-7,-1,3],[-1,2,5,-1]])

In [22]:
dvalues = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [23]:
# Relu activation's derivative
drelu = np.zeros_like(z)
drelu[z > 0] = 1
print(drelu)

[[1 1 0 0]
 [1 0 0 1]
 [0 1 1 0]]


In [24]:
# the chain rule
drelu *= dvalues
print(drelu)

[[ 1  2  0  0]
 [ 5  0  0  8]
 [ 0 10 11  0]]


## page 37 copy matrix to not replace values

In [25]:
import numpy as np

In [26]:
# Example layer outputs
z = np.array([[1,2,-3,-4],[2,-7,-1,3],[-1,2,5,-1]])

In [27]:
dvalues = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [28]:
drelu = dvalues.copy()

In [29]:
drelu[z<=0] = 0

In [30]:
print(drelu)

[[ 1  2  0  0]
 [ 5  0  0  8]
 [ 0 10 11  0]]
