In [1]:
import numpy as np

In [2]:
# Passed in gradient from the next layer
# for the purpose of this example we're going to usea 
# a vector of 1's

In [19]:
dvalues = np.ones((1, 3))
print(dvalues)

[[1. 1. 1.]]


In [20]:
# we have 3 sets of weights - one set for each neuron
# we have 4 inputs, thus 4 weights
# recall that we keep weights transposed

In [22]:
weights = np.array([[0.2, 0.8, -0.5, 1],[0.5, -0.91, 0.26, -0.5],[-0.26, -0.27, 0.17, 0.87]])

In [23]:
weights = weights.T

In [24]:
weights

array([[ 0.2 ,  0.5 , -0.26],
       [ 0.8 , -0.91, -0.27],
       [-0.5 ,  0.26,  0.17],
       [ 1.  , -0.5 ,  0.87]])

In [14]:
# sum weights of given input
# and multiply by the passed in gradient for this neuron

In [25]:
dx0 = sum(weights[0]) * dvalues[0]

In [27]:
sum(weights[0])

0.43999999999999995

In [29]:
dx1 = sum(weights[1]) * dvalues[0]
dx2 = sum(weights[2]) * dvalues[0]
dx3 = sum(weights[3]) * dvalues[0]

In [30]:
dinputs = np.array([dx0, dx1, dx2, dx3])

In [31]:
print(dinputs)

[[ 0.44  0.44  0.44]
 [-0.38 -0.38 -0.38]
 [-0.07 -0.07 -0.07]
 [ 1.37  1.37  1.37]]


In [34]:
np.dot(dvalues, weights.T)

array([[ 0.44, -0.38, -0.07,  1.37]])