In [7]:
# Common loss class
class Loss:
    #calculates the data and regularization losses
    #given model output and ground truth values
    def calculate(self, output, y):
        
        #Calculate sample losses
        sample_losses = self.forward(output , y)
        
        #Calculate mean loss
        data_loss = np.mean(sample_losses)
        
        #return loss
        return data_loss

In [8]:
# Cross-entropy loss
class Loss_CategoricalCrossEntropy(Loss):
    # Forward pass
    def forward(self, y_pred, y_true):
        
        # Number of samples in a batch
        samples = len(y_pred)
        
        # Clip data to prevent division by 0
        # Clip both sides to not drag mean towards any value
        # numpy.clip(a, a_min, a_max)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)
        
        # Probablities for target values - 
        # only if categorical labels
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]
            
        # Mask values - only for one-hot  encoded labels
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped * y_true, axis=1)
            
        #Losses
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods
            
        
        
        

In [17]:
import numpy as np
softmax_outputs = np.array([[0.7, 0.1, 0.2],
                   [0.1, 0.5, 0.4],
                   [0.02, 0.9, 0]])
# class_targets = [0, 1, 1] #dog, cat, cat
class_targets = np.array([[1, 0, 0],
                 [0, 1, 0],
                 [0, 1, 0]])

In [18]:
loss_function = Loss_CategoricalCrossEntropy()

In [19]:
loss = loss_function.calculate(softmax_outputs, class_targets)

In [20]:
loss

0.38506088005216804

In [21]:
# TESTING THE CROSS-ENTROPY LOSS CLASS
# Number of samples in a batch
samples = len(softmax_outputs)
print(samples)


3


In [22]:
# Clip data to prevent division by 0
# Clip both sides to not drag mean towards any value
# numpy.clip(a, a_min, a_max)
print("Before clip function")
print(softmax_outputs)
y_pred_clipped = np.clip(softmax_outputs, 1e-7, 1-1e-7)
print("After clip function")
print(y_pred_clipped)

Before clip function
[[0.7  0.1  0.2 ]
 [0.1  0.5  0.4 ]
 [0.02 0.9  0.  ]]
After clip function
[[7.e-01 1.e-01 2.e-01]
 [1.e-01 5.e-01 4.e-01]
 [2.e-02 9.e-01 1.e-07]]


In [24]:
class_targets.shape

(3, 3)

In [25]:
len(class_targets.shape)

2

In [27]:
print(class_targets)
correct_confidences = np.sum(y_pred_clipped * class_targets, axis=1)
print(correct_confidences)

[[1 0 0]
 [0 1 0]
 [0 1 0]]
[0.7 0.5 0.9]


In [34]:
if len(class_targets.shape) == 1:
    correct_confidences = y_pred_clipped[range(samples), class_targets]
    # Mask values - only for one-hot  encoded labels
elif len(class_targets.shape) == 2:
    correct_confidences = np.sum(y_pred_clipped * class_targets, axis=1)
print(correct_confidences)

[0.7 0.5 0.9]


In [35]:
negative_log_likelihoods = -np.log(correct_confidences)

In [36]:
negative_log_likelihoods

array([0.35667494, 0.69314718, 0.10536052])

In [37]:
np.sum(y_pred_clipped * class_targets, axis=1)

array([0.7, 0.5, 0.9])